### ISSUE TITLE
Not an issue but a request

### ISSUE THREAD

**Issue by johnlockejrr** [DT-UCPH/sp#51]
I can't find the actual text of the Samaritan Pentateuch, should I ask Prof. Schorch for it?

**Comment by MartijnNaaijer** [comment]
Hi, you can find the text of the individual words here: https://github.com/DT-UCPH/sp/blob/main/tf/3.4.1/g_cons_utf8.tf

**Comment by johnlockejrr** [comment]
> Hi, you can find the text of the individual words here: https://github.com/DT-UCPH/sp/blob/main/tf/3.4.1/g_cons_utf8.tf

Thanks, I'm aware of that, but how to join that in verses, chapters?

**Comment by MartijnNaaijer** [comment]
1. Install text-fabric with `pip install text-fabric`.
2. Run the following code in a notebook:

```python
from tf.app import use
A = use('dt-ucph/sp', hoist=globals())

# print verse
n = T.nodeFromSection(('Genesis', 1, 1))
print(T.text(n))
print()

# print chapter
n = T.nodeFromSection(('Genesis', 1, ))
print(T.text(n))
print()

# print book
n = T.nodeFromSection(('Genesis', ))
print(T.text(n))
```

Let me know if that works.

**Comment by johnlockejrr** [comment]
I will try it. Thank you so much!

**Comment by johnlockejrr** [comment]
Added github tocken, same error:

```
The requested TF-app is not available offline
        ~/text-fabric-data/dt-ucph/sp/app not found
rate limit is 5000 requests per hour, with 4998 left for this hour
        connecting to online GitHub repo dt-ucph/sp ... connected
        app/__checkout__.txt...downloaded
        app/__init__.py...downloaded
        app/app.py...downloaded
        app/config.yaml...downloaded
        app/static...directory
                app/static/logo.png...downloaded
        OK
<IPython.core.display.HTML object>
The requested data is not available offline
        ~/text-fabric-data/dt-ucph/sp/tf not found
rate limit is 5000 requests per hour, with 4980 left for this hour
        connecting to online GitHub repo dt-ucph/sp ... connected
No directory tf/3.3.1 in #d34b301c5874a64cf0e65fae72269152c0297ec5Will try something else
        FailedNo directory tf/3.3.1 in #893bec3898e2e07adfe7eb8806485fe62039c468        FailedThere were problems with loading data.
The Text-Fabric API has not been loaded!
The app "dt-ucph/sp" will not work!
Traceback (most recent call last):
  File "tst.py", line 6, in <module>
    n = A.nodeFromSection(('Genesis', 1, 1))
AttributeError: 'TfApp' object has no attribute 'nodeFromSection'
```

**Comment by MartijnNaaijer** [comment]
I see. Could you try to run it in a jupyter notebook? That should work in a slightly different way.

**Comment by johnlockejrr** [comment]
Sure, here:

![Ubuntu 23 10 1 64-bit-2024-02-16-21-32-00](https://github.com/DT-UCPH/sp/assets/16368414/482c94ad-edac-46a7-a703-9b5ef1ef933d)

**Comment by johnlockejrr** [comment]
Tried like this also, in jupyter notebook:

```
from tf.app import use
SP = use('dt-ucph/sp', hoist=globals())
Fsp, Lsp, Tsp = SP.api.F, SP.api.L, SP.api.T
PENTATEUCH = ['Genesis']
def reconstruct_pentateuchal_verses(F, L, T, text_feature):
    """For each verse of the Pentateuch in a given dataset, the text of each verse is reconstructed.
    Output:
    verse_texts: dict   Keys are verse label (tuple with book, chapter verse), values are reconstructed text (str).
    """
    verse_texts = {}

    for verse_node in F.otype.s('verse'):
        bo, ch, ve = T.sectionFromNode(verse_node)
        if bo in PENTATEUCH:
            verse_text = ''
            word_nodes = L.d(verse_node, 'word')
            for word_node in word_nodes:
                word_text = eval(f'F.{text_feature}.v(word_node)')
                trailer = F.trailer.v(word_node)
                if not word_text:
                    continue
                elif not trailer:
                    verse_text += word_text
                else:
                    verse_text += word_text + ' '

            verse_texts[(bo, ch, ve)] = verse_text.strip()
    return verse_texts    
    
sp_verses = reconstruct_pentateuchal_verses(Fsp, Lsp, Tsp, 'g_cons')
for label, mt_verse_text in mt_verses.items():
    sp_verse_text = sp_verses.get(label, '')
    print(label)
    print(sp_verse_text)
```

Got this error:

```
Traceback (most recent call last):
  File "/home/incognito/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/tf/advanced/app.py", line 619, in findApp
    app = appClass(
          ^^^^^^^^^
  File "/home/incognito/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/tf/advanced/app.py", line 213, in __init__
    linksApi(self, silent=silent)
  File "/home/incognito/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/tf/advanced/links.py", line 181, in linksApi
    header(app, allMeta=silent == VERBOSE)
  File "/home/incognito/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/tf/advanced/links.py", line 225, in header
    nodeInfo = _nodeTypeInfo(app)
               ^^^^^^^^^^^^^^^^^^
  File "/home/incognito/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/tf/advanced/links.py", line 553, in _nodeTypeInfo
    levels = api.C.levels.data
             ^^^^^^^^^^^^
AttributeError: 'Computeds' object has no attribute 'levels'
TF is not loaded
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 3
      1 from tf.app import use
      2 SP = use('dt-ucph/sp', hoist=globals())
----> 3 Fsp, Lsp, Tsp = SP.api.F, SP.api.L, SP.api.T
      4 PENTATEUCH = ['Genesis']
      5 def reconstruct_pentateuchal_verses(F, L, T, text_feature):

AttributeError: 'NoneType' object has no attribute 'api'
```

**Comment by johnlockejrr** [comment]
Worked finally, had to do it like this:

```
from tf.app import use
A = use('dt-ucph/sp', version='3.3')
api = A.api
T = api.T
# print verse
n = T.nodeFromSection(('Genesis', 1, 1))
print(T.text(n))
print()
```

And clone the `DT-UCPH/sp` data locally.

![image](https://github.com/DT-UCPH/sp/assets/16368414/c68593ca-fe3b-40a3-ae1d-58d7e0a6c01e)

**Comment by MartijnNaaijer** [comment]
Okay, great!
